name: Terraform Apply - EKS Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: TheMashcraft/terraform-reusable-workflows/.github/workflows/aws-terraform-apply.yml@main
    with:
      terraform_dir: './'                   # Directory containing Terraform configuration
      terraform_version: '1.5.2'            # Version of Terraform to use
      aws_iam_role: 'arn:aws:iam::747693303791:role/GithubActionsRole'  # AWS IAM role to assume
      aws_region: 'us-east-1'               # AWS region for deployment
      plan_file: 'terraform.tfplan'         # Path to save the Terraform plan file
    permissions:
      id-token: write
      contents: read
